# Generated by Django 3.0.5 on 2020-04-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20200425_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментырий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
