# Generated by Django 3.0.5 on 2020-04-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='riddle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.Riddle', verbose_name='Загадк11а'),
        ),
    ]
